TARGET = XK-1A
APP_NAME =
USED_MODULES = module_locks
XCC_FLAGS = -g -O3 -save-temps
VERBOSE = 0

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
